# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCk/gtmTfKa3EzKDWUYQQGKuhZN+KWhpy36HOyDhLZS6Wd08nEw5nP2qlQRPyvGr/ewGR9QPdS4lfuFBY3O7xTSQXfGWzTAwF0XEso5gW0pwQgANh16Zk6uQWUfB2BBGRtVCnqFugpy/jLxbGyZdWCa6FupMsFg16cfTjfp4tcm07pb/KIGxkGntdRc96DX/EHJQIpC/9roGY598h57WISeh8eTg5UzT3twgzQEg8X9yhk52ZZmWOALs/zbDrqE9fHCVpnhES0X85b8nCCvdar55nu+gK+GzwZqXA5pvKJ5LyIkoqmDg2XG7NRb6s8VDwZSupq59QL00j5FKGLLRjUiv35wYMUarnX1DkvM8GcLAN4EoG9lNK/2Ce942C3GsKi3NWk8PtnwyX8w5vNUsz0Or9ficl+aFkwXqQSA54dVtZPYMM3t334f0K1TH/P0mo82HMgnB4sd1SXMTN/yiEVSx5vxEoJQpkLfAZ/mUo2ozgTXyLEtrepNqmTJv5HaitPKEKdHalFtNQV8NhgTWBWHHSQdB/6rPaCgLgN/emKJ4P3WJyn9bKP3O1Y1DnQOxgjUEGH9MnId23y/Gw7PeOtgOHf6ErLgRntoC4uQEWMwOvx2+mQKIcYAHmRvAnTlFTlBLrUM/Zu5O72FdTEuvzIIWftnoEgAt5Lu9jS3ZjU1rw== alfonsorey@microsoft.com'
    sshKeySecureFile: 'AzureRmPipeline-repokey'
    
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'f799acb6-27df-4b01-ad21-eb5ba7d2bffe'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG-AzureRmPipeline'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/Alfonso-Rey/AzureRmPipeline-repo/blob/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName AzureRmPipeline-repo'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

- script: |
    git config --global url."git@github.com:Alfonso-Rey/AzureRmPipeline-repo".insteadOf "https://github.com/Alfonso-Rey/AzureRmPipeline-repo"
    go build
    displayName: 'Build the binaries'
